# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "playground"
client_id = "32d41d292f9d966cf0c25ccc9bdc5ee4"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
dev_store_url = "squirrels-and-squirrels.myshopify.com"
